stages:
  - prepare
  - build

build_image:
  stage: prepare
  image: docker:latest
  script:
    - docker build -f Docker/Dockerfile -t template .

build:
  image: template:latest
  stage: build
  script:
    # Configure
    - cmake -S . -B build
    # Build
    - cmake --build build/
  artifacts:
    paths:
      - build/
