stages:
  - prepare
  - build

build:
  image: build-template
  stage: build
  script:
    # Configure
    - cmake -S . -B build
    # Build
    - cmake --build build/
  artifacts:
    paths:
      - build/
    # set it to delete artifacts
    expire_in: 1 minute