FROM ubuntu:kinetic

RUN apt update -y && apt install -y \
	cmake \
	build-essential\
    pkg-config\
    libx11-dev\
    libxcb-keysyms1-dev\
    libqt5svg5-dev\
    libqt5x11extras5-dev\
    libpcre2-dev\
    libpcre++-dev\
    libx11-xcb-dev\
    libxrandr-dev\
    libxinerama-dev\
    libxcursor-dev\
    libxi-dev\
    python3\
    python3-pip
